# Generated by Django 4.0.4 on 2022-05-14 20:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='users/avatar.jpg', upload_to=accounts.models.user_directory_path),
        ),
    ]
